# This workflow has been disabled in favor of Jenkins pipelines
name: cluster-plan-disabled
on:
  push:
    branches-ignore:
      - '**'  # This ensures this workflow never runs on any branch

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow disabled
        run: echo "This workflow has been disabled in favor of Jenkins pipelines"