# This file is used to disable all GitHub Actions workflows
name: disabled-workflows
on:
  push:
    branches-ignore:
      - '**'  # This ensures this workflow never runs on any branch

jobs:
  disable-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Disable all workflows
        run: echo "All workflows disabled in favor of Jenkins pipelines"